# Generated by Django 4.1.2 on 2022-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='conferencechair',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='systemadmin',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
