# Generated by Django 4.1.2 on 2022-10-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=0, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
