# Generated by Django 4.1.2 on 2022-10-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastName',
        ),
    ]
