# Generated by Django 4.1.2 on 2022-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_users_approved_remove_users_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Paper',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
