# Generated by Django 4.1.2 on 2022-11-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_author_status_conferencechair_status_reviewer_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bidded_paper',
            table='bidded_paper',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='paper',
            table='paper',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
