# Generated by Django 4.1.2 on 2022-11-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_comment_sent_date'),
        ('website', '0004_reviewrating'),
    ]

    operations = [
    ]
