# Generated by Django 4.1.2 on 2022-10-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_name_author_name_remove_author_paper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencechair',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reviewer',
            old_name='Name',
            new_name='name',
        ),
    ]
