# Generated by Django 4.1.2 on 2022-11-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_merge_0004_comment_sent_date_0004_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='review',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='website.review'),
            preserve_default=False,
        ),
    ]
