# Generated by Django 4.1.2 on 2022-10-30 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
