# Generated by Django 4.1.2 on 2022-10-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_paper_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(to='website.author'),
        ),
    ]
