# Generated by Django 4.1.2 on 2022-10-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_paper_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='description',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
