# Generated by Django 4.1.2 on 2022-11-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_review_bidded_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidded_paper',
            name='status',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='bidded_paper',
            name='submission_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='saved_file',
            field=models.FileField(upload_to='website/files'),
        ),
    ]
