# Generated by Django 4.1.2 on 2022-11-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_bidded_paper_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidded_paper',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
