# Generated by Django 4.1.2 on 2022-11-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_reviewer_id_bidded_paper_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(default='Not Accessed', max_length=255),
        ),
    ]
