# Generated by Django 4.1.2 on 2022-11-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='uploaded_by',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
